name: SHAW
description: Keep it short. Keep it simple.


nav:
    HOME: /
    ARCHIVE: /archives/
    GALLERY:  /

excerpt_link: Continue Reading

aboutMeImg: /aboutme.jpg

github: https://github.com/yiliashaw
twitter: https://twitter.com/YiliaShaw
weibo: http://weibo.com/kathleenxiao

themeLink: https://github.com/yiliashaw/hexo-theme-prince

