#header
name: GENKUN
description: Sometimes NAIVE.
favicon: /favicon.png
ga: ''

#nav
nav:
    HOME: /
    ARCHIVE: /archives/
    GALLERY:  /gallery/
    ABOUT: /about/

#post
excerpt_link: Continue Reading


#about me
aboutMeImg: /aboutme.jpg

github: https://github.com/GenkunAbe
twitter: https://twitter.com/GenkunAbe
weibo: https://weibo.com/genkunabe

#copyright
themeLink: https://github.com/GenkunAbe/hexo-theme-hiruko

cdn:
    mathjax: https://cdn.mathjax.org

## enable disqus powered comment system
comment:
    id: genkun